### ISSUE TITLE
Allow Offline Indexing

### ISSUE THREAD

**Issue by squinky86** [squinky86/STIGQter#106]
A local copy of the CCIs and Controls should be provided with STIGQter to allow offline, CRN, or classified-network processing. It will also keep the application working when public.cyber.mil moves or changes files unexpectedly.

**Comment by TheCleverEpithet** [comment]
The way we have worked around this in the past is load STIGQTer on the low side. Import CCIs. Save the database a "Blank Fresh DB.stigqter" and move that file to the high side with the tool. Then File, Open.

**Comment by squinky86** [comment]
Right now, the stable release of STIGQter doesn't work because DISA removed the old rev4 CCI list last week from public.cyber.mil (though the rev5 list contains the old CCIs in it). I'm going through the last tests of 1.1.4 so I can hurry up and get that out so that a broken version of STIGQter isn't listed as the stable release. This would keep things from going stale on stable builds.

**Comment by TheCleverEpithet** [comment]
Ah, I didn't realize that DISA has replaced the Rev 4 and moved to newly minted Rev 5 so quickly. I figured the Government would move slower than that.
