### ISSUE TITLE
XCCDF / SCAP Import into Checklist

### ISSUE THREAD

**Issue by user20000000000** [squinky86/STIGQter#11]
Mentioned by another on the team.  If this will serve as a replacement for STIG Viewer is should also include the capability import XCCDF SCAP results from automated SCAP scans (e.g. SCC) to populate a given Checklist File.

**Comment by momo040** [comment]
Also there are tools that have been created that export a modified XCCDF format that can be imported into STIG viewer. 

Below is the output format. The file extension was changed from XML to for the purpose of uploading to GitHub,

[windows_10_Partial_STIG_Results.txt](https://github.com/squinky86/STIGQter/files/2733562/windows_10_Partial_STIG_Results.txt)

**Comment by squinky86** [comment]
Accepted as a new feature for 0.1.1
