### ISSUE TITLE
[Enhancement] Adding Prevalence to CCIs Tab of DFR

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#110]
Currently the "CCIs" Tab of the DFR Report (which is great and awesome - we love and depend on it) currently lists CCIs and the mapped STIG checks like this:

![1](https://user-images.githubusercontent.com/36047865/161864267-aa3214a6-b29b-4f51-a071-ab964dc18b67.JPG)

This contains duplications of the same STIG ID (since it was presumably found on multiple assets/hosts). This is not a big deal, but it could be an opportunity for a very useful new metric / piece of information that the tool might be able to tease out of the database.

Could the "Checks" field of the "CCIs" tab of the DFR Report be modified to format the content something like the following?

![2](https://user-images.githubusercontent.com/36047865/161864288-c53a3912-cb7c-467e-ac54-9a31879122be.JPG)

An important distinction with this request would be that the 'X of Y Samples' and the percentage would need to be based on the total number of assets/hosts in the database that had that particular STIG/Benchmark applied to them, even if some were Not A Finding.  So the query would have to be updated somewhat.  

Altering the previous example a bit, assume that the ASD STIG was applied/assessed on 6 Applications, but check SV-222437r508029_rule was only Open on 3 of them.  In this scenario the "Checks" field would be something like:

![3](https://user-images.githubusercontent.com/36047865/161864292-8a986776-8f38-488b-8cbb-dab914de56c5.JPG)

The reason for this request is that some organizations may require/desire an analysis if the 'prevalence' or 'breadth' of the vulnerability or STIG Finding throughout their network or at least throughout the sampled devices they have data for - E.g., "Was it on every host or only a few or just a single one?" and being able to cite this for each STIG Check at the CCI level would be very useful.

**Comment by TheCleverEpithet** [comment]
The example only had one STIG check for ease of reading.  Obviously for CCIs with multiple STIG checks mapped to them, the STIG rule text lines would stack like they do now within the cell to capture all of the mapped STIG Checks like it does currently.

**Comment by TheCleverEpithet** [comment]
If this is doable, and you choose to include the percentage in the text string, it should be rounded to the nearest whole number, or at most one decimal place to conserve character/text space.

**Comment by squinky86** [comment]
Love this idea! I should be able to keep up with the calculations a bit. For the total samples, I plan to only count the Open and Not a Finding checks (not applicable or not checked will not count towards this metric).

**Comment by squinky86** [comment]
I am hitting an edge case where someone could have overridden the CAT severity on one asset but not another. I had to remove the "CAT" severity from your example, but everything else is working in my tests. Source code commit incoming...
