### ISSUE TITLE
[Request] Additional Control-Based Data/Info from STIGs in DFR Output

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#116]
Request for new data be added to the Detailed Findings Report output from the Reports menu. Content and location described below. This is needed to comply with requirements from leadership in our organization. 

Detailed Findings Report Spreadsheet > “Controls” Tab/Worksheet > Columns C and D

Add Column C:

‘Control Technical Deficiency Description’

This needs to contain a concatenation of all of the “Discussion” text strings from All Open STIG/SRG Checks that are associated with this Control (i.e., All Open STIG checks mapped to All CCIs under this control). These Discussion values should be separated by a blank line break. This entire string should begin with “Technical Vulnerabilities: ”, followed by the concatenated string.

If this concatenated string is longer than 2,500 Characters (including spaces), it should be truncated at 2,500 characters and the string “This has been truncated due to character limitations; please, see the STIG Checklist files for more information. ” should be appended to the end. 

If there are no Open STIG/SRG Checks associated with the Control (i.e., No Open STIG checks mapped to Any of the CCIs under this control), state “Documentation Deficiency”

Add Column D:

‘Control Technical Recommendations’

This needs to contain a concatenation of all of the “Fix Text” strings from All Open STIG/SRG Checks that are associated with this Control (i.e., All Open STIG checks mapped to All CCIs under this control). These Fix Text values should be separated by a blank line break. The entire string should begin with “Technical Recommendations: ” following by the concatenated string.

If this concatenated string is longer than 4,900 Characters (including spaces), it should be truncated at 4,900 characters and the string “This has been truncated due to character limitations; please, see the STIG Checklist files for more information. ” should be appended to the end. 

If there are no Open STIG/SRG Checks associated with the Control (i.e., No Open STIG checks mapped to Any of the CCIs under this control), state “Documentation Deficiency”

**Comment by squinky86** [comment]
Resolved in git; will be in next version.
