### ISSUE TITLE
DFR Control Tab Truncation Method for Text in Columns C and D

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#123]
The method used to truncate the text in the DFR Control Tab in Columns C and D seems to be causing an issue where some data is lost.  While some data loss when truncating for character limitations is likely inevitable, I would like to suggest a different method for truncating the strings that might retain more of the most pertinent data.

Currently, all the Discussion Text strings (no matter their length) are concatenated together for all the open STIG IDs for a given control and then at the end of this process if the concatenated string is over X Characters it is truncated and the text "This has been truncated due to character limitations; please, see the STIG Checklist files for more information." is appended to the end. (Granted this is very likely exactly what was asked for in the original feature request, but user feedback has been coming in over the last few weeks that would indicate this may not have been the best way).  This can cause some STIG IDs further down the list to be omitted entirely if there are large discussion strings early in the list or a large number of STIG IDs total for that control. The text for fix/recommendations in Column D appears to work the same way. 

Could the truncation method instead be to check the length of each STIG Discussion text as it is added to the master concatenated string, and if each individual Discussion string is longer than 250 characters truncate the individual string (tack on a shorter "Truncated due to character limit." at the end), then add this to the master concatenated string for the control, then remove the overarching truncation for the whole string at the end.  This way the user can have a full list of unique STIG IDs for that control without worrying about some being cut off due to truncation, and they can manually edit the string later if the result is still too long for eMASS. This would be both columns C and D, for the discussion and fix texts. 

So remove truncation at the end on the final concatenated string, and replace it with iterative truncation for each sub-string as each is added to the overall concatenated string.

![image](https://github.com/squinky86/STIGQter/assets/36047865/161d1431-b48a-4dc6-b42b-ac2717de3ea1)

**Comment by squinky86** [comment]
Allocating 2472 characters to each stig check, then dividing it by the total number of stig checks, then truncating based on the header and each stig's allocation of how much space it can have in the cell. That should resolve the issue, but it'll need tested and may look bad when there are tons of checks.
