### ISSUE TITLE
Checklist listing/display content 

### ISSUE THREAD

**Issue by user20000000000** [squinky86/STIGQter#13]
Currently in the Listing of Checklist Files that have been imported into the tool the only Identifying data element displayed is the host name (see screenshot).  There will likely be many CKLs for each host in an assessment and it would be useful to have more that just the host name displayed to identify what checklist is represented. 

E.g. "<Hostname> - <STIG Name> - <Version and Release of the STIG> - <Date CKL File was Last Edited>

or something like that.  The Host Name, STIG name, and STIG Version and Release are especially useful to see displayed and readily accessible. (If there are 100+ CKLs having to open each one to check the version and release can be tedious, if there are 12 CKLs for a given host it is tedious to have to open each one to see what STIG it is, etc.)

![ckl listing](https://user-images.githubusercontent.com/46379344/50700300-ca886100-100f-11e9-814c-fb1e6d32e52f.png)

**Comment by squinky86** [comment]
STIGQter manages the CKLs by asset, not by STIG (the way asset management was intended to be done). When you open the CKL for A1V04, all STIGs that have been imported should be visible and selected in the A1V04 tab. But I do agree with the tediousness of seeing what STIGs have been applied to this asset. I have some ideas of how this can be afforded to the user from the selection screen more completely and will work on it for 0.1.1.
