### ISSUE TITLE
Keyboard short cuts for editing STIG results

### ISSUE THREAD

**Issue by momo040** [squinky86/STIGQter#14]
A functionality in STIG viewer that the team enjoys is while highlighting one or multiple SV-******_rule by pressing the following keys a action will happen:

O = make the highlighted rules open

N = make the highlighted rules Not a Finding

R = make the highlighted rules Not Reviewed

X = make the highlighted rules Not Applicable

**Comment by squinky86** [comment]
This should already be working in the current beta…
