### ISSUE TITLE
Cannot import MS SQL 2012 Database AND Instance STIGs 

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#29]
Cannot import MS SQL 2012 Database AND Instance STIGs.  While these are downloaded as one file it appears that only the shorter "Instance" STIG will import into the tool.  I have tried to create separate Zip files for both STIGs and import them separately but it does not recognize the MS SQL Server 2012 "Database" STIG.

**Comment by squinky86** [comment]
DISA botched the naming of the V1R18 STIG and quickly came out with an update. Download the latest STIG and it should work properly. Closing this bug as fixed upstream.
