### ISSUE TITLE
[Feature Request] Open CCI Level Report with High Water Mark STIG Severity

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#30]
[Feature Request] It would be very useful to have a new Report/Export function that would meet the following requirements.  

This report/export should but the format example provided, but contain Only contain text/output for Non-Compliant/Open CCIs.  If the CCI is Compliant/Closed these fields would be blank (even if there are Compliant STIG results or Compliant Verbiage from an eMASS TRE import).

Attributes/Columns: 

AP Acronym, CCI #, Raw Severity, Counter Measures, Comments.

Attribute/Column Definitions:

AP Acronym: This is the CCI level control identifier (e.g. AC-2(1).1, AU-12(3).4, etc. - note the "dot notation" for indicating which CCI/Sub-control is being referenced).

CCI #: This is the CCI number formatted as 000000 as STIG Qter already formats these numbers. This is somewhat duplication of the previous attribute to uniquely identify the CCI, but this is needed. 

Raw Severity: This column should have the values "CAT I", "CAT II", or "CAT III".  This should be determined by the high water mark or Highest severity finding associated with is CCI.  For example CCI 000366 has 50 STIG Findings mapped to it and there are no CAT I findings mapped to it but there are CAT II and CAT III findings mapped to it, then the value should "CAT II".  If there are no STIG findings associated this implies a documentation based finding and the value should be "CAT III"

Counter Measures: This should be set to the value of "VH" for now.  This can be expounded upon in the future perhaps.  

Comments: This field should contain the concatenated list of all Open STIG Findings AND any comments from the "Test Results" column of any previously imported eMASS TR Export data.  For example if there are no STIG findings associated, but the user has imported a TRExprt spreadsheet that contains a test result for this CCI stating "Non-Compliant - The document required did not be the CCI requirements." that comment should appear here.  If there are both STIG Findings and TRE comments, the STIG Results should be displayed first. 

For context this is an attempt to automate the Army NETCOM SCA-V Risk Assessment Workbook population based on the output from this tool.

**Comment by squinky86** [comment]
Accepted as a feature for 0.1.6

**Comment by TheCleverEpithet** [comment]
If implementation of this feature is hampered by the lack of availability of a public/unclassified listing of AP Acronym (XX-00(0).X format) style identifiers for the CCIs, we could we modify this feature request and just remove the AP Acronym column from this report. 

The primary objective of this report/output is to get the Max CAT I/II/III Severity or high watermark for each individual CCI.  The AP acronym is present in the NETCOM spreadsheet, but so is the CCI number and we can key on just the CCI.  

If that makes this easier and/or more palatable, it would still get us the key information that we need for the RAW which is high watermark CAT severity per CCI.

**Comment by squinky86** [comment]
The Detailed Findings Report has the high-watermark severity per CCI on it already in the "CCIs" sheet. I'd like to leave this issue open, though, so we can use the Assessment Procedure notation used by eMASS in the future.

**Comment by TheCleverEpithet** [comment]
This is excellent!  I just saw this. However, the problem identified in Issue #37 affects this output.  

Specifically, for example if I import a STIG Checklist that has SV-29201r2_rule marked Open and then generate a DFR, the CCI tab only has CCI-000164 listed with the CAT II high watermark and SV-29201r2_rule list - which is correct - however, CCI-000163 and CCI-000162 are also mapped to this STIG check and should also be listed on the CCI tab as having a high watermark CAT II open/NC STIG check associated.
