### ISSUE TITLE
[Feature Request] Re-Map all "Orphaned" findings to CM-6 CCI-000366

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#31]
Re-Map all "Orphaned" STIG findings (i.e. either not mapped to a CCI at all OR is mapped to a CCI but that CCI is not present in the eMASS TR import spreadsheet if one has been imported) to CM-6/CCI-000366.

**Comment by squinky86** [comment]
Accepted as a feature for 0.1.6.
