### ISSUE TITLE
DFR - CCI Column Format

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#36]
If the Format of the CCI number could be just 000000 (as text I think - the same format as the CCI column in the TRExport report?) that might be useful as if we ever wanted to search from one sheet to another (vlookups, comparisons, etc.) in excel being able to key on the CCI attribute without having to change the format manually (stripping out "CCI-" and then formatting as text so excel doesn't strip off leading zeros, etc.) would be convenient.

**Comment by squinky86** [comment]
I'd like to keep this one as a number. If you need to do vlookups on CCIs where they're stored as strings in one sheet and numbers in another, you can use the following conversions:

- =VLOOKUP(TEXT(A1, "CCI-000000"), ...) - this will convert the number format in the spreadsheet to text
- =VLOOKUP(VALUE(A1), ...) - this will convert the text format "00000" to a number format
- =VLOOKUP(VALUE(RIGHT(A1, LEN(A1) - 4)), ...) - this will convert the text format "CCI-00000" to a number format

And my favorite:
- VLOOKUP(VALUE(RIGHT(TEXT(A1,"CCI-000000"),LEN(TEXT(A1,"CCI-000000")) - 4)), ...) - this will convert the number format in the DFR to a string, strip off the "CCI-", and convert it back to a number format!
