### ISSUE TITLE
Add Non-STIG Non-Compliant CCIs to DFR CCIs Tab

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#39]
While the main purpose of the CCIs Tab in the DFR is to see the CAT rating for associated STIG findings, it seems that the CCIs tab of the DFR (the tab that shows the list of Non-Compliant CCIs and their High Watermark) does not include CCIs that are made Non-Compliant from the eMASS Import Spreadsheet (e.g. CCIs that have been marked as Non-Compliant Manually by an analyst during documentation review due to a policy or documentation based deficiency and has No mapped STIG findings).  

Could these Non-Compliant CCIs be added to the CCIs Tab of the DFR with the Value of "CAT III"?  And, In order to avoid a loss of fidelity regarding which Non-Compliant CAT III CCIs were from STIG findings and which were from Policy/Documentation findings, set the value in the Checks column (where STIG IDs are normally listed) to "Documentation Findings"?

**Comment by TheCleverEpithet** [comment]
This should be give by priority over any other feature requests from user TheCleverEpithet.

**Comment by squinky86** [comment]
I'm implementing this per your recommendations with a slight difference:
The comment is "Imported/Documentation Findings" rather than just "Documentation Findings"

**Comment by squinky86** [comment]
Also, this rolls up to the Control-level sheet added by issue #39.

**Comment by TheCleverEpithet** [comment]
Thank you, sir!!  This appears to be the last piece of the puzzle for working this tool fully into our internal processes!
