### ISSUE TITLE
STIG Import Issue

### ISSUE THREAD

**Issue by 4merFatMan** [squinky86/STIGQter#40]
Does not import U_MS_SQL_Server_2012_V1R19_STIG.zip correctly.  It only imports the database but not the instance.

**Comment by squinky86** [comment]
This is a duplication of issue #29. DISA botched it and named them both "SQL Server 2012" without specifying which was the database and which was the instance. They inadvertently did the same thing with V1R18 and quickly pushed out a fixed V1R18 when it was identified. I'm emailing disa.stig_spt@mail.mil about this. If they don't fix it on their end, it's going to cause a mess when people try to import it into eMASS.

**Comment by squinky86** [comment]
DISA ticket STS-023401 has been created to fix this issue.

**Comment by squinky86** [comment]
DISA will fix this in their next quarterly release. I'll leave this issue open until it's resolved upstream.

**Comment by squinky86** [comment]
U_MS_SQL_Server_2012_V1R20 is now released and works correctly.
