### ISSUE TITLE
eMASS Test Results Report Does Not Retain APs

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#42]
While the raw STIGQter DB does not contain assessment procedures, would it be possible to retain the Assessment Procedures (Column I) and Implementation Guidance (Column H) when a Test Result Export (TRE) spreadsheet containing this information from eMASS is Imported into STIGQter?  This way once the eMASS Test Results report is generated from STIG Qter (assuming a TRE from eMASS has been imported) this information is still present to better allow for better analysis.  

Since these values come from eMASS, I agree that they should not show up in STIG Qter reports unless they have been Imported from an eMASS TRE by the user first. 

Currently putting the fresh TRE from eMASS "through" STIG Qter results in "gaining" test results for all the STIG checks, but "Losing" the Assessment Procedure and Implementation Guidance text/information in the process.

**Comment by squinky86** [comment]
I cannot give a stern enough warning against using Assessment Procedure Numbers (AP#). These were standardized before 800-53rev2. Now, they are not. And they change regularly. DO NOT RELY ON AP#.

With that being said, I'll add it in with the above caveat and acknowledgement that AP#s will not show up for any CCIs that are not imported.

**Comment by TheCleverEpithet** [comment]
Sorry for the confusion.  I do not mean the "AP Number" (I recall we spoke about that previously), but the Assessment Procedures Text in Column I (for example "The organization conducting the 
inspection/assessment obtains and examines the Access Control Policy... ...").  

I am OK with not incorporating the "AP Number" scheme based on our previous conversations.
