### ISSUE TITLE
"Date Tested" field is Populated for Blank Rows in TRE Report

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#43]
Scenario:

Import a blank Test Results Export (TRE) spreadsheet from eMASS for your system.  Import all your STIG Checklists to get STIG Qter to map all of your STIG checks to the appropriate CCI to create test results for import into your eMASS system record. 

Issue:

When doing this it will almost always result in the eMASS Test Results Report Output containing CCI rows that do not have STIG test results (i.e. they were in the TRE Export from eMASS but don't have STIG checks mapped).  Currently STIG Qter populates the "Date Tested" field for ALL of the CCIs/Rows in this report output even if there are no test results created, no Tested By name added, or no Compliance status provided.  

This could cause eMASS to flag these are problematic when the eMASS Test Results report output spreadsheet is imported back into eMASS.  Is it possible to prevent the "Date Tested" field from being populated IF (1) it was blank when the source TRE was imported and (2) there were no STIGs mapped to the CCI and therefore no test results added by STIG Qter?

Note: If there was a value here when the "Import eMASS Sheet" function was used by the user (e.g. for manual/imported test results), it should retain what ever date was provided by the import UNLESS STIGQter is providing New Test Results (e.g. adding/mapping STIG checks.).  If it was blank in the users TRE import and no STIG mapped test result are being created it should remain blank.

**Comment by squinky86** [comment]
I'm putting an update into git right now that I *THINK* fixes this, but I don't have access to a ton of eMASS test result reports to test it with. I'm leaving this open until I hear from you that it's fixed. I imagine it's going to need some fine-tuning.

**Comment by TheCleverEpithet** [comment]
This appears to be fixed now.
