### ISSUE TITLE
Inherited CCIs are not determined from eMASS TRExport

### ISSUE THREAD

**Issue by twillgamble** [squinky86/STIGQter#48]
Inherited CCIs that do not appear in the Test Results Export from eMASS that have compliant or non-compliant vulnerabilities mapped will be added to the test result report generated after importing the STIGs and checklists.

**Comment by squinky86** [comment]
When you click "Remap CM-6" on the Main tab, does this solve the issue?

If not, can you please create a test case (don't upload it here - email it to me directly as it may contain FOUO data) for me to work on?

**Comment by squinky86** [comment]
Got your email and found the bug - thanks!

Notes for myself in case I mess this up later:
The remapper got confused in the situation where a STIG check was mapped against multiple CCIs where some of the CCIs were part of the system and some were not. It further failed when it tried to remap the one CCI to CM-6 when the STIG was already mapped to another CCI that was valid. The logic in the code is now:

Does the STIGCheck map against a CCI that is not in the imported system? if so, remove the mapping.
Is the the STIGCheck mapped against a CCI? If not, map it to CCI-366.
