### ISSUE TITLE
Issue opening JRE for Unix V1R2 STIG and Checklist

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#49]
If you import the JRE for Unix V1R2 STIG and then import a checklist created with that same version of the STIG, STIGQter pops up saying that there is no matching STIG loaded for that checklist and the Checklist import fails. 

Note: We worked around this by creating a new checklist using V1R3 of this STIG and then everything works correctly.  This is probably an issue with the older V1R2 STIG, but I wanted to let you take a look at it if you were interested in case the issue (whatever it is) crops up elsewhere.

**Comment by squinky86** [comment]
I can't find a copy of the V1R2 STIG; please send me a copy when you get the chance.

**Comment by TheCleverEpithet** [comment]
Not sure how we even came up with a CKL from that version of the STIG...  I checked back in the archives as far as 2017 and V1R3 was still the newest one for this STIG as far back as I could look.  This is probably just an issue with a REALLY old STIG.  I didn't realize how old this was... This can probably be closed as we shouldn't have been using such as old version.
