### ISSUE TITLE
eMASS TRE Report CCI column in Text instead of Number format?

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#50]
The nightly build I downloaded yesterday appears to no longer output the CCIs in the TRE report as numbers.  

The eMASS TRE Report CCI column appears to be in Text instead of Number format.  Excel gives the "Number stored as Text" warning on all CCI cells and formula references to those cells that compare to CCI numbers in other spreadsheets no longer work.  Once I told Excel to convert to numbers on those cells the formula references worked again.

Did the format change when the TRE report generation code was rewritten?

**Comment by squinky86** [comment]
Yep - this is from eMASS. It will not import if it's stored as a number (eMASS expects this field to be text). All other reports should have a CCI-formatted number except for the eMASS test result import/export.

**Comment by TheCleverEpithet** [comment]
Ok.  Appears to be an issue with my other spreadsheet.  This can be closed out.  Sorry about that.
