### ISSUE TITLE
Checklist View Filter Missing Filter for "NA"?

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#51]
When viewing/editing a STIG checklist in STIGQter, there is a filter (Labeled "Checks" with two drop downs, one for status and one for CAT).  

The status filter can be set to "O", "NR", "NF, "All", and "NC".  

However there is no filter for "NA".  What does the "NC" filter look for?  Can we add an "NA" filter option as well?

**Comment by squinky86** [comment]
Good catch! Fixed the typo. NC should have been NA. It'll get fixed in the nightly build.

**Comment by squinky86** [comment]
For reference, this filter follows the status in the original STIGViewer:
All: no filter
O: Open
NR: Not Reviewed
NF: Not a Finding
NA: Not Applicable
