### ISSUE TITLE
Re-Map Un-Mapped STIG Checks on Quarterly Import?

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#56]
It is not clear (I have not successfully tested this yet) when using the Download Quarterly button if all the imported STIGs have their un-mapped STIG checks automatically mapped to CM-6.  This might be done in the background that I just cannot see. 

When you import an individual STIG a prompt appears to tell the user that the un-mapped STIG checks are being mapped to CM-6 (e.g. click ignore to continue, etc.).  

However, when the user does the Download Quarterly button and all the STIGs are imported, this prompt does not appear and it is not clear that all the un-mapped STIGs from the entire quarterly are being mapped to CM-6.

**Comment by squinky86** [comment]
On the original test, it generated over 3000 prompts that a STIG check was not mapped correctly. They are remapped to CM-6 automatically and quietly in the background when they are mapped to CCIs that don't exist.

If you have imported an eMASS Test Result Import excel file, you will need to click on the "Remap CM-6" button after importing more STIGs. This takes the CCIs that are mapped to legitimate CCIs and remaps them to CM-6 when the legitimate CCIs are not in your baseline.
