### ISSUE TITLE
Crash When Importing CKL without matching STIG

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#61]
Issue found in v1.0.1 Nightly build from 20 Feb 20.

When importing a Checklist file for which there is no matching STIG loaded, the "STIG/SRG Not Found" alert box appears, but the application seems to crash and go into a Not Responding state.  The popup box never populates with content about which CKL file or STIG/SRG is in question.  

This occurred with multiple different STIGs and did not appear to be isolated to any one STIG or SRG.

**Comment by squinky86** [comment]
Should be fixed in latest nightly (push 417c0d7)
