### ISSUE TITLE
Date Stamp for Nightly Build File Name?

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#62]
Is it possible (and more importantly is it too much trouble) to add a date stamp to the default filename of the nightly build? 

Currently is defaults to "STIGQter-nightly.zip" and the exe contained therein is "STIGQter-nightly.exe".  Could this be changed to STIGQter-nightly_YYYY-MM-DD.exe, etc.?

I rename it manually each time, but multiple other folks download it (and don't rename it) on different days and it can be difficult to determine which ones are which.

**Comment by squinky86** [comment]
datestamp added
