### ISSUE TITLE
Error Extracting Nightly Build Zip (2020-03-05)

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#65]
When I download the nightly build from the link below, and try to extract or unzip the .zip file I (and others) get the error in the attached screenshot and we cannot unpack and use the executable.  This was observed on 2020-03-05. 

https://www.stigqter.com/STIGQter-nightly.zip

![extraction_error](https://user-images.githubusercontent.com/36047865/75986945-9aa74880-5eb4-11ea-9085-cdce714b81be.PNG)

**Comment by squinky86** [comment]
Rebuilding now. If it's not working tomorrow, I'll turn off compression. For now, use 7-zip.

**Comment by squinky86** [comment]
fixed with latest nightly

**Comment by TheCleverEpithet** [comment]
Appears to be working as of 2020-03-10:0700
