### ISSUE TITLE
eMASS/AM CM-6 Mapping Option for Orphaned STIG Checks

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#70]
Request the Option to have STIGQter Map Unmapped STIG Findings to Match Asset Manager in eMASS.

Currently STIGQter re-maps all Unmapped STIG findings to CM-6.5 (CCI-000366).  Honestly this makes the most sense in general. 

However, Asset Manager in eMASS re-maps all Unmapped STIG findings to all CM-6 CCIs in the given system’s baseline (this does result in the same STIG check having duplicate mappings to each of these CCIs).

This causes conflicts between the Test Results generated by STIGQter after injesting a STIG Checklist (e.g. the TRE report from STIGQter that can be imported into eMASS) and that same STIG Checklist when it is imported directly into Asset Manager in eMASS by the end system owner. 

Request, please, that the User be prompted by STIGQter upon importing STIGs containing Unmapped STIG checks or STIG Checklists containing Unmapped STIG checks (whenever it does it currently), with a choice to re-map Unmapped STIGs EITHER: (1) Only to CM-6.5 / CCI-00366 (as it is now), OR (2) to re-map them to all CM-6 CCIs in the imported TRE eMASS Sheet to match what eMASS Asset Manager would do. 

Note that this is a separate functon from the "Re-Map CM-6" button that is currently in STIG Qter, which remaps STIG checks that do have DISA CCI mappings, but that map to CCIs that are outside the current system's baseline from the imported TRE/eMASS-Sheet.  This could be be added here if it is easier.  We are just wanting an option for STIGQter to remap orphaned STIG checks the same way eMASS/Asset Manager does.

**Comment by squinky86** [comment]
What I'm running into are some systems that have marked CM-6 as N/A. The logic is as follows as I'm seeing it:

1. If the user has not imported an eMASS test result, map to all possible CM-6 CCIs
2. If the user has imported an eMASS test result AND CCIs under CM-6 are applicable, remap to those CCIs
3. If the user has imported an eMASS test result AND no CCIs under CM-6 are applicable, remap to CCI-366

This should keep problems from occurring, even if users decide to import STIGs before importing eMASS test results. Can you see any potential problems I may be missing?
