### ISSUE TITLE
Signed Installer & sha512

### ISSUE THREAD

**Issue by Asguard128** [squinky86/STIGQter#73]
On a windows computer w/ a hardened OS, the stigqter installer will kick back an error that the installer is not signed w/ a certificate. 
There is an irony here. 
Also, there should be a hash to verify the installer download before running to verify the download's sucess.

**Comment by squinky86** [comment]
Hashes are here: http://www.stigqter.com/STIGQter-1.0.0.hashes.txt

Certificates for code signing are not free, and I don't have permission to use my CAC to sign this project yet. If you know where I can get a code signing cert cheap or free, I'll take it!

**Comment by Asguard128** [comment]
Hi,
STIGQTer could set up their own CA and if users utilize the app, they can
download the stigQTer public CA and install it in their root trust.

**Comment by squinky86** [comment]
I opted for cacert.org. Release 1.0.1 will be signed with a key from CAcert.
