### ISSUE TITLE
NC Checks Not Taking Precedence when Remapping CM-6

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#74]
Failed "out of baseline" STIG checks being remapped to CM-6 CCIs upon Clicking the "Remap CM-6" button do not appear to take precedence over Passed Checks in the eMASS Test Results report.  

If there are both passed and failed STIG checks that get remapped to a CCI, any Failed Checks should take precedence and the Test Result should be Non-Compliant and list the failed STIG Checks only - Only if there are no Failed STIG Checks should the Passed checks cause the CCI to have a Compliant test results in this report. 

------------------------

For Example: 

Rule ID: SV-86837r3_rule was Failed and originally mapped to CCI-001668 in the STIG.  This CCI is not in the baseline for the system being reviewed (not in the Import eMASS Sheet TRE).  This CKL is imported into STIGQter.

Rule ID: SV-8532r3_rule was Passed and originally mapped to CCI-001098 in the STIG. This CCI is not in the baseline for the system being reviewed (not in the Import eMASS Sheet TRE). This CKL is imported into STIGQter.

The user clicks the "Remap CM-6" Button (with the "All CM-6" Checkbox checked prior to importing the STIGs and CKLs). 

The user generates the eMASS Test Results Report.  The CM-6 CCIs (other than CM-6.5 which has many other STIG checks directly mapped) in this report contain the following values:

"Compliant.
The following checks are compliant: 
HOSTNAME: SV-8532r3_rule"

**Comment by squinky86** [comment]
Confirmed - I was able to reproduce. Tracking down the bug now...
