### ISSUE TITLE
DFR Report Contains Duplicate "ID" Numbers

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#75]
Tested in nightly pulled 14 May at 1448CDT.

Case: New DB, Import CCIs, Check "Remap to All CM-6" Checkbox, Import STIGs, Import CKLs containing unmapped STIG checks, import eMASS Sheet, Click "Remap CM-6" button, go to reports and generate Detailed Findings Report file.

Column A in the Findings worksheet of the the DFR workbook contains multiples/duplicates of ID numbers for different/distinct rows of the spreadsheet. 

This appears to be tied to the STIG Rule ID (Column H) - Every instance of STIG Rule SV-99999r1_rule would have "ID" 5, for example, even though other attributes in the row like CCI were different.

**Comment by squinky86** [comment]
Confirmed fixed in last commit
