### ISSUE TITLE
DFR Report Not Listed Mapped Controls

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#77]
DFR from the Reports menu appears to list correct CCIs for mapped STIG checks in the report, but it lists all controls as "ZZ-0" for all findings.  This is from the nightly build downloaded on 7/1/20. Reported by user 4merFatMan; the .stigqter file and example DFR being sent out of band.

**Comment by squinky86** [comment]
Confirmed. The issue is caused because NIST updated their website (https://nvd.nist.gov/800-53/Rev4) and it is not being properly indexed. Working this now.

**Comment by squinky86** [comment]
Issue should be fixed. Updating to Qt 5.15.0 on the build server and will test the nightly build.

**Comment by squinky86** [comment]
The solution I tried earlier didn't work. The nightly tonight should have a working fix.

**Comment by squinky86** [comment]
This is still an issue. Trying again to track it down today.

**Comment by squinky86** [comment]
resolved and tested with latest nightly.
