### ISSUE TITLE
Autoload of STIGs

### ISSUE THREAD

**Issue by squinky86** [squinky86/STIGQter#78]
When importing several CKLs, the quantity that fail to import due to having the wrong version(s) or types of STIGs loaded into the tool is high. An easier auto-load of STIGs would be preferred when possible. Feature requested by Trey.

Discussion: For now, the non-FOUO STIGs can be indexed at their latest version, but that does little to help the analysis of a system that was scanned before the release of a new version of a STIG. Being able to maintain a repository of all possible STIGs would be helpful and save time.

**Comment by squinky86** [comment]
Idea: I've created a service that indexes the current list of STIGs. When a CKL is loaded that is not in the database, STIGQter can reach out to the web service and request the URI for the STIG/SRG. The user would then have an option to either automatically download the detected STIG/SRG (default option), or display a message with an error (current option) that has the link to download the STIG if they are connected to the internet.

The script indexing the list of STIGs will run every weekend to stay reasonably up-to-date, and it will only work for unclassified, publicly released STIGs/SRGs.

**Comment by TheCleverEpithet** [comment]
I like the that idea.

Users should note, though, that if they load a CKL made with v1r1 of the STIG and DISA has updated the STIG to v1r2 (i.e., removes v1r1 from cyber.mil), this approach would not be able to automatically download their specific version of the STIG used in their CKL if it is not still the most current one on the site.
