### ISSUE TITLE
Host/Asset Name Should Be Case Insensitive

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#82]
Use Case:

Import CCIs and STIGs.

Create Checklist: "host" as the host name
Create Checklist: "Host" as the host name
Create Checklist: "HOST" as the host name

Note these checklists are for different STIGs (e.g. Operating System STIG and two Application STIGs, etc.)

Import all of the checklists in STIGQter.

STIGQter then creates three different "Assets" or hosts based on the different cases of the letters (host, Host, and HOST) with each individual seperate STIG associated with each one.  Is this by design or should it convert all host names to all upper or lower case when ingesting CKLs and comparing to existing asset names to keep STIGs associated with the same asset/host?

![caps](https://user-images.githubusercontent.com/36047865/92165849-5104cf80-edfd-11ea-8103-e73d9278cf8d.PNG)

**Comment by TheCleverEpithet** [comment]
Note: Asset Manager in eMASS does not appear to differentiate based on upper/lower case in the host name field.  For example if I import these three checklist files referenced above, eMASS will detect them as automatic matches to an existing asset named "host" regardless of case.

**Comment by squinky86** [comment]
This requires a minimal database change. The change shouldn't affect anyone, but the databases created with 1.0.2 will be slightly different than the databases created with 1.0.0 and 1.0.1. That way, if someone created two "assets" with different capitalizations in 1.0.0 or 1.0.1, they can continue to use that database in 1.0.2, but 1.0.2 will prevent that from happening (instead merging imported checklists together based on the first representation of the hostname encountered).

What this means is that if you create a database in <=1.0.1 that encounters the bug in this issue, the bug will persist, even if you upgrade STIGQter to a new version. This prevents the scenario of STIGQter deleting, overwriting, and merging two different assets together. But if you create the database in 1.0.2, the bug will no longer be present.
