### ISSUE TITLE
Controls revert to ZZ-0 in reports under certain conditions

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#84]
It appears that if you check the "Remap to all CM-6" Checkbox before Importing the CCIs that something weird happens and thereafter (even after starting over with a brand new database, and even deleting the .db file and generating a new one) all controls in reports continue to be listed as ZZ-0 in reports (CCIs appear to be listed correctly, just the controls are ZZ-0). 

This may also be related to a new format of the TRE in eMASS.  I have not had a chance to test this yey

**Comment by TheCleverEpithet** [comment]
This may be tied to a very recent update to the TRE format from eMASS... One of the team members reported that there is a New Column in the TRE (Column E may have changed)

**Comment by squinky86** [comment]
Confirmed. It's from the eMASS update last week. I'll try to walk through my list of tests with eMASS to see what all has changed before releasing 1.0.2.

**Comment by squinky86** [comment]
side effect of issue #85; should be fixed now.
