### ISSUE TITLE
eMASS TRE Format Change 17 SEP 2020

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#85]
The Test Results Expoert TRE (or "eMAS Sheet") format has changed:

A new column has been inserted in the TRE format from eMASS:

Formerly Column E was "AP Acronym"

Now Column E is "Control Implementation Narrative"

The "AP Acronym" column is still present (Now Column F), but all columns past Column E have been shifted one column to the right from their previous location. 

This will affect the eMASS TRE Report Output, as well as functions tied to the "Import eMASS Sheet" button.

**Comment by squinky86** [comment]
Confirmed. Chris Lovejoy showed me the new column this morning. It was added in the update last week. Will be fixed in 1.0.2 after I run a suite of tests to see if anything else changed.

**Comment by squinky86** [comment]
Fixed in commit 0097319f7b72bd7f92afde8eee657ccf1b4a3f5f; will be released in 1.0.2
