### ISSUE TITLE
Multiuser Support (enhancement request)

### ISSUE THREAD

**Issue by STIGnewb** [squinky86/STIGQter#87]
Two of the biggest things I see missing from STIGviewer 
1) being web based (vs downloaded app)
2) lack of collaboration

Use Case:  I manage a large security project with many components and and about 25 people.  At any one time there might be different people working the same STIG on the same platform.  The current products don't support this model, which gets messy both from a working perspective and reporting.  

Having a web based model with others being able to see the system as a whole is needed.   It also allows a pathway to scaled structured growth.

**Comment by squinky86** [comment]
I have thought about doing this many times, and in fact started this project as a web interface. In initial testing, users kept stepping on each other while working on the same STIG check, and setting up a polling construct to update the interface for when other users made changes became very complicated. I'm going to leave this request open for now, as I'm working on another project idea that may be able to solve this, but it's going to be a separate project.

**Comment by squinky86** [comment]
I'm not planning on making a web version any time soon, but I have tested network support in the app for larger teams.
