### ISSUE TITLE
Add STIG Results to TRExport Spreadsheet for eMASS Test results

### ISSUE THREAD

**Issue by user20000000000** [squinky86/STIGQter#9]
After being able to import the TRExport Spreadsheet from eMASS (see separate ticket), There needs to be a function within the tool to populate eMASS compatible test results (e.g. the TRExport spreadsheet format) from Compliant and Non-Compliant STIG findings from the imported STIG Checklists.  

E.g. If STIG ID V-99999 is Non-Compliant in a given imported checklist file there should be a function to detect that this STIG ID is mapped to CCI-999999 and then create a test result such as "Non-Compliant.  DISA has established a mapping between this CCI and STIG ID V-99999; this STIG ID was found to be Open during the on site inspection and as a result this CCI was assessed as Non-Compliant."  

Conversely this should also be done with STIG IDs that are found to be Not a Finding in the STIG Checklists to create Compliant test results for mapped CCIs such as "Compliant.  DISA has established a mapping between this CCI and STIG ID V-99999; this STIG ID was determined to be Not a Finding during the on site inspection and as a result this CCI was assessed as Compliant."

**Comment by squinky86** [comment]
This is already done under "file → export eMASS sheet." The additional TRExport functionality will be tracked in issue #8.
