### ISSUE TITLE
"Save CKLs" to Export All Monolithic CKLs

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#91]
In v1.0.2, when you click on "Open CKL" for an asset, the "Save CKLs" (Plural) button no longer appears to export ALL of the asset-based multi-STIG Checklists like it originally did.  Seems to do the same thing as the "Save CKL" (Singular) button and only export that one asset in a CKL.

**Comment by squinky86** [comment]
There are currently three different ways to export CKL(s):

- Asset -> Save CKL will build a single, monolithic CKL file with all STIGs selected for the asset
- Asset -> Save CKLs will have you select a folder to export individual CKLs for each STIG in the Asset
- Reports -> STIG CKLs will perform the Save CKLs action for every Asset on the selected folder

I'm also updating the documentation to reflect the three different options.

**Comment by TheCleverEpithet** [comment]
All three of those options are good and valid.   But there needs to be a forth way.  This forth way should build single/monolithic CKL files with all STIGs for each host, for each asset in the DB.  

So if Host1 has 3 STIGs, Host2 has 4 STIGs, Host3 has 9 STIGs, .... and finally Host 22 has 2 STIGs - then I would love to be able to click one button and get 22 Checklist files (each one with multiple STIGs for all the STIGs associated with each host) one for each host, rather than having to click each asset and click 'Asset -> Save CKL' 22 times.

**Comment by squinky86** [comment]
Nope - doesn't yet exist. Reopening issue. Good catch!
