### ISSUE TITLE
Error and Crash - Control Not Found

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#93]
Pulled down v1.1.0 on 16 March at 1000AM

Opened Application.  Clicked File New to create a new database.

Clicked Import CCIs.  This got almost to the end, but then started throwing errors and crashed.  When I try to reopen the app, all I get are the errors in the screenshot.
![Capture](https://user-images.githubusercontent.com/36047865/111338976-60cf5d00-8645-11eb-8acf-396de6f2b6ed.PNG)

Even after closing this version, the database appears to be corrupted for older version of STIGQter and I have to manually delete the database .db file and then start up an old version of STIGQter to get it to rebuild it in the old format, as a work around to get older version to continue working.

**Comment by squinky86** [comment]
Confirmed. NIST released 800-53 rev 5.1. With it came a whole new website (https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/800-53) that provides the data, and some of the data we rely on is currently missing. This is going to be a big change and will take a few days to recreate the data miners.

**Comment by squinky86** [comment]
Ok, I took the opportunity to rewrite a large chunk of the code and optimize it a bit. It should index RMF controls and CCIs much faster now, and it's no longer dependent on parsing the NIST website (at the expense of having some control description information now missing in the generated test result reports).
