### ISSUE TITLE
Blank CCI List

### ISSUE THREAD

**Issue by 4merFatMan** [squinky86/STIGQter#95]
Selecting Import CCIs is not properly importing the CCI list.

**Comment by squinky86** [comment]
The certificate for public.cyber.mil expired on 5/2/2021 and they haven't renewed it. Temporary workaround - set your clock back to 5/1/2021 and you'll be good to go.

**Comment by squinky86** [comment]
I'm leaving this open until the government fixes their expired cert. In the event they don't fix it in the next week or two, I'll have to find a more permanent workaround.

**Comment by squinky86** [comment]
Email from DISA: "This is a known issue and is currently being worked. Thank you for reaching out. There is no ETR but we are working our best to restore to full operation." They're on it ;)

**Comment by squinky86** [comment]
Certificates have been updated. If this happens again, I'll implement a "don't check certificates" feature.
