### ISSUE TITLE
Default Filters in eMASS TRE Report

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#96]
Column "S" is not included in the default set of filterable headings in the TRE Report, which can lead to jumbled filters that do not include that column (this column is the existing test result or self assessment value, so it being offset from the original row when other columns are filtered on can be problematic).  Request extending default filters on row 6 to include column S.

**Comment by squinky86** [comment]
Fixed. I plan to release 1.1.2 at the end of the month which adds the POA&M report and fixes this issue.
